name: Cancel
on:
  workflow_run:
    workflows: ['automerge', 'build', 'codeql-analysis']
    types:
      - requested
permissions:
  actions: write
jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@a0cb97d26853c69945fd18bdc6d6862b41707fdf
        name: Cancel Previous Workflow Runs
        with:
          workflow_id: ${{ github.event.workflow.id }}
